### ISSUE TITLE
OrderStatus value seems to have no affect for amazonMws.orders.search()

### ISSUE THREAD

**Issue by moggiex** [bhushankumarl/amazon-mws#10]
Howdy Bhushankumar,

It appears setting the value of 'OrderStatus' to an array of valid values doesn't seem to have an effect to the results, is it be passed to the API correctly?

An example is...

```
amazonMws.orders.search({
        'Version': '2013-09-01',
        'Action': 'ListOrders',
        'SellerId': 'REMOVED',
        'MWSAuthToken': 'REMOVED',
        'MarketplaceId.Id.1': 'REMOVED',
        'OrderStatus': ["Unshipped", "Pending"],
        'MaxResultsPerPage' : 2, // def: 100, max 100
        'CreatedAfter' : new Date(1, 1, 2018),
        //'LastUpdatedAfter': new Date(13, 12, 2017),

    }, function (error, response) {
        if (error) {
            console.log('error ', error);
            return;
        }
        console.log('response', response);
    });
};
```
And the orders are returned, but it appears the OrderStatus was completely ignored as the orders that are returned are in multiple statuses, such as "Shipped".

**Note:** Multiple order statuses can be set, eg Pending and Unshipped as per the docs here http://docs.developer.amazonservices.com/en_IN/orders-2013-09-01/Orders_ListOrders.html

> A list of OrderStatus values. Used to select orders with a current status that matches one of the status values that you specify.

Also using the value of :

`'OrderStatus': "Unshipped",`

Gives this response from Amazon:

```
error  { Type: 'Sender',
  Code: 'MalformedInput',
  Message: 'Unexpected list element termination',
  RequestId: '34ead115-4407-428b-a5b8-REMOVED' }
```

Matt

**Comment by moggiex** [comment]
Ah ha, 

`&OrderStatus%5B0%5D=Unshipped&OrderStatus%5B1%5D=Pending`

Just caught this in AmazonMwsResource.js on line 371 as the path being sent. that value is incorrect with it's added "[0]" & [1] as I believe it should be:

`&OrderStatus=Unshipped,Pending`

Matt

**Comment by moggiex** [comment]
Resolved, do this instead :)

```
       "OrderStatus.Status.1": "Unshipped",
        "OrderStatus.Status.2": "PartiallyShipped",
        "OrderStatus.Status.3": "Pending",
        "OrderStatus.Status.4": "Shipped",
```

**Comment by bhushankumarl** [comment]
@moggiex Exactly, It does support field style instead of the Array style.
You can use as per below : 

	amazonMws.orders.search({
		'Version': '2013-09-01',
		'Action': 'ListOrders',
		'SellerId': 'REMOVED',
		'MWSAuthToken': 'REMOVED',
		'MarketplaceId.Id.1': 'REMOVED',
		'MaxResultsPerPage' : 2, // def: 100, max 100
		'CreatedAfter' : new Date(1, 1, 2018),
		//'LastUpdatedAfter': new Date(13, 12, 2017),
		'OrderStatus.Status.1': "Unshipped",
		'OrderStatus.Status.2': "PartiallyShipped",
		}, function (error, response) {
			if (error) {
				console.log('error ', error);
				return;
			}
			console.log('response', response);
		});
	};
