### ISSUE TITLE
Warning: a promise was rejected with a non-error: [object Object]

### ISSUE THREAD

**Issue by sottenad** [bhushankumarl/amazon-mws#100]
First off, thanks for your effort putting this together. I found a small improvement that will cut down on warnings in the console and is probably best practice around handling errors returned from the MWS services. It appears that on line 75 of lib/AmazonMwsMethod.js, when the promise is rejected, the `err` object passed to it is just the error object returned from Amazon, not a true js `Error`. I forked it and made a correction that clears that warning up for me - I'd be happy to issue a pull request. Thoughts?

**Comment by bhushankumarl** [comment]
@sottenad Is it passing all jshint & test cases?
