### ISSUE TITLE
[Request] Discard Bluebird as dependency

### ISSUE THREAD

**Issue by marcospampi** [bhushankumarl/amazon-mws#102]
Since nodejs have promises by its own, maybe it's time to just discard Bluebird polyfill, and there's a big reason for that:
```ts
if( res$ instanceof Promise )
    ...then
```
This would not work so far, as constructors differ.
This is as easy as remove one line from both `AmazonMwsMethod.js` and `AmazonMwsMethod.basic.js`

**Comment by bhushankumarl** [comment]
@marcospampi 
Have you done that change?

**Comment by marcospampi** [comment]
I didn't had the occasion to update my fork, it works as expected changing it inside `node_modules`.
Sorry for this lazy-*ss rensponse.

**Comment by bhushankumarl** [comment]
@marcospampi 
It has been fixed in https://github.com/bhushankumarl/amazon-mws/pull/129
