### ISSUE TITLE
GetReportListByNextToken supported?

### ISSUE THREAD

**Issue by wrod7** [bhushankumarl/amazon-mws#103]
Hello, does this package support action: 'GetReportListByNextToken' ? doesnt seem to be working correctly.

```
const nextReportRL = await amznmws.reports.search({
        Version: '2009-01-01',
        Action: 'GetReportListByNextToken',
        SellerId: process.env.AMAZON_MWS_SELLER_ID,
        NextToken: nextToken
      })
```

**Comment by marcospampi** [comment]
```js
const nextReportRL = await amznmws.reports.search({
        Version: '2009-01-01',
        Action: 'GetReportListByNextToken',
        SellerId: process.env.AMAZON_MWS_SELLER_ID,
        MWSAuthToken: YOUR_TOKEN,
        NextToken: nextToken
      })
```
You're missing the token, as a good practice I reccomend you to wrap the common args as such:
```js
const common = {
        Version: '2009-01-01',
        MWSAuthToken: YOUR_TOKEN,
        SellerId: process.env.AMAZON_MWS_SELLER_ID,
};
//...then
const nextReportRL = await amznmws.reports.search({
        ...common,
        Action: 'GetReportListByNextToken',
        NextToken: nextToken
})
```
Or better, using a function
```js
function ReportsSearch( method, args = { } ) {
    return amznmws.reports.search({
        Version: '2009-01-01',
        MWSAuthToken: YOUR_TOKEN,
        SellerId: process.env.AMAZON_MWS_SELLER_ID,
        Action: method,
        ...args
      });
}
```
Sorry for being too invasive in how-to-do-it, I'm more than one year into this, and this client is barebone sugar, what's bitter is Amazon MWS as the service they provide.

**Comment by wrod7** [comment]
@marcospampi thanks for the reply.

when i use mws [scratchpad](https://mws.amazonservices.com/scratchpad/index.html) with action 'GetReportRequestListByNextToken' it doesn't require MWSAuthToken. where can I find my MWSAuthToken?

**Comment by marcospampi** [comment]
This isn't scratchpad.
Look at the example request under Reports/GetReportRequestListByNextToken in the official documentation.
