### ISSUE TITLE
Huge Reports Issue

### ISSUE THREAD

**Issue by beastmike1** [bhushankumarl/amazon-mws#104]
Hi, we are having troubles processing some reports from sellers with a huge catalogue, like 600k products for each marketplace. 

For example, an open listing report from one of that sellers after been parsed for your library and saved to a txt file, it weighs more than 200 mb.

I think that a way to pipe the report result directly to a file it could be better than caching all the response in a variable in that cases, would that be possible? 

Thanks.

**Comment by marcospampi** [comment]
The the http stream isn't accessible by the current interface, but is in 
`https://github.com/bhushankumarl/amazon-mws/blob/master/lib/AmazonMwsResource.js`
As for now you can use the pseudo-argument `__RAW__` that will return the blob of it.
You could expose the stream by adding another pseudo-argument, as I did back then for the blob one.

**Comment by beastmike1** [comment]
To do it in a streaming fashion as said in java examples in [AmazonDocumentation](https://developer.amazonservices.co.uk/javaclients)

in Reports -> GetReportSample.java

> // Note that depending on the type of report being downloaded, a report can reach 
   // sizes greater than 1GB. For this reason we recommend that you _always_ program to
   // MWS in a streaming fashion. Otherwise, as your business grows you may silently reach
   // the in-memory size limit and have to re-work your solution.

**Comment by jesusvalle** [comment]
@bhushankumarl, @marcospampi, this will be so interesting for my project too.
