### ISSUE TITLE
FeedSubmissionResult not returning error.

### ISSUE THREAD

**Issue by zeeshanpaalo** [bhushankumarl/amazon-mws#108]
Hey. This is not giving any errors, it just gives response although when I use MWS scratchpad, I have fatal error due to a Inventory Template error. 
amazonMws.feeds.search({
        'Version': '2009-01-01',
        'Action': 'GetFeedSubmissionResult',
        'SellerId': 'SELLER_ID',
        'MWSAuthToken': 'MWS_AUTH_TOKEN',
        'FeedSubmissionId': FeedSubmissionId
    }, function (error, response) {
        if (error) {
            console.log('error ', error);
            return;
        }
        console.log('response', response);
    });

**Comment by zeeshanpaalo** [comment]
The Callback is always invoked with response even though there is an error when checking with MWS scratchpad.

**Comment by bhushankumarl** [comment]
@zeeshanpaalo Not sure, But this is working as expected. Please feel free to reopen this issue if you still facing an error.
