### ISSUE TITLE
forced to pass itemCondition for GetLowestPricedOffersForASIN

### ISSUE THREAD

**Issue by fr3shn3ss** [bhushankumarl/amazon-mws#111]
itemCondition is optional . However, when I comment it out, I'll get a 400 error. Am i missing something here? 

Thanks

**Comment by bhushankumarl** [comment]
@fr3shn3ss 
Can you send me an actual request?

**Comment by bhushankumarl** [comment]
This API call is working perfectly fine. Please feel free to reopen if the issue still persist for you.
