### ISSUE TITLE
throttle info missing in response

### ISSUE THREAD

**Issue by brandon-zeng** [bhushankumarl/amazon-mws#118]
I can get the data correctly, but throttle info is missing. 

the following is the throttling info part in the response:

  "Headers": {
    "x-mws-quota-max": "unknown",
    "x-mws-quota-remaining": "unknown",
    "x-mws-quota-resetson": "unknown",
    "x-mws-timestamp": "2020-01-06T21:23:49.390Z",
    "content-type": "text/xml",
    "content-charset": "unknown",
    "content-length": "106281",
    "content-md5": "unknown",
    "date": "Mon, 06 Jan 2020 21:23:50 GMT"
  }

**Comment by bhushankumarl** [comment]
@brandon-zeng 
Yeah, for some APIs MWS is not sending throttling details.
