### ISSUE TITLE
Incomplete response in GetFeedSubmissionResult

### ISSUE THREAD

**Issue by noemiearcane** [bhushankumarl/amazon-mws#120]
When using the method `GetFeedSubmissionResult`, the `data` object in the response only returns the first row (I'm expecting 8000 lines). 
Since the raw response returned by the amazon api (`MWS:AmazonMwsResource responseString` in DEBUG mode) has a line break after its first row, it is likely to be a parsing problem.

Response received:
```
{
  data: [
    {
      'original-record-number': '1',
      SKU: 'XXXXX',
      'error-code': '13013',
      'error-type': 'Erreur',
      'error-message': "We're unable to complete your request because this SKU is not in the Amazon catalog. If this was a deleted SKU, wait 24 hours before resubmitting it. If you tried to add this SKU to the Amazon catalog before, check your data and correct any errors before resubmitting."
    }
  ]
}
```

**Comment by bhushankumarl** [comment]
@noemiearcane 
Please check the error message. It states what is actual problem with your SKU.
