### ISSUE TITLE
Is there any way to pass proxy params when create mws instance?

### ISSUE THREAD

**Issue by hoist1999** [bhushankumarl/amazon-mws#126]
Dear Developer:

**Comment by hoist1999** [comment]
Dear Developer:
I need to use dynamic proxy when i create mws instance, but when i check the source code, the only way to pass proxy parameter is use process.env. Can you add a parameter to constructor by which i can dynamic change the proxy. thanks.

**Comment by bhushankumarl** [comment]
@hoist1999 
It has been fixed in https://github.com/bhushankumarl/amazon-mws/pull/129
