### ISSUE TITLE
Problem with JSON response when multiple items are returned

### ISSUE THREAD

**Issue by edwardsph** [bhushankumarl/amazon-mws#127]
I am trying to call GetLowestOfferListingsForASIN with multiple ASIN numbers but the response is being processed incorrectly in AmazonMwsResource.js. The problem code is:
```javascript
if (response[requestParamsJSONCopy.Action + 'Result'] !== undefined) {
  response = response[requestParamsJSONCopy.Action + 'Result'];
}
response.ResponseMetadata = ResponseMetadata;
response.Headers = ResponseHeaders;
response.StatusCode = statusCode || 'unknown';`
```
When using multiple ASINs the response is structured as:
```xml
<GetLowestOfferListingsForASINResponse>
   <GetLowestOfferListingsForASINResult/>
   <GetLowestOfferListingsForASINResult/>
   <ResponseMetadata/>
</GetLowestOfferListingsForASINResponse>
```
In the JSON equivalent GetLowestOfferListingsForASINResult is an array not a single object so the code above sets the response to the array. The subsequent calls to add ResponseMetadata, Headers and StatusCode fail. The top level response should always be an object.

It would be worth adding tests that use multiple input Ids where this is allowed by the API.

Other than this problem - this is working very well for me - thanks.

**Comment by bhushankumarl** [comment]
@edwardsph 
Can you provide the ASIN with which you are facing a problem?

**Comment by edwardsph** [comment]
@bhushankumarl, The issue was not any specific ASIN but that the API is designed to take a list of ASIN. I'm afraid I partially wasted your time as I realise now it is possible to add keys to an array since is also behaves like an object. I had been confused by seeing in the debugger the response variable being type "Object {}" or "Array[2]" depending on whether I used 1 ASIN or 2. I assumed it was a problem that this was not consistent. Seeing no tests using multiple inputs, I assumed this had been on oversight. I see now that if I check the structure I can deal with either.
Examples:
```javascript
ASIN = 0583305571
Res = {
  "ASIN": "0583305571",
  "Product": { }
  "ResponseMetadata": { },
  "Headers": { },
  "StatusCode": 200
} 

ASIN = 0583305571, 1498289223
Res = [
  {
  "ASIN": "0583305571",
  "Product": {  }
  },
  {
  "ASIN": "1498289223",
  "Product": {  }
  },
  "ResponseMetadata": { },
  "Headers": { },
  "StatusCode": 200
]
```
So I can get the headers from the response whether there is 1 result or more. However, to process the results consistently I do this:
```javascript
    const resultArray = Array.isArray(res) ? res : [res];
```
Is this something that it would be useful to add to the docs to explain how the results differ in the 2 circumstances?
Thanks for your time
Pete

**Comment by bhushankumarl** [comment]
@edwardsph 
That is preety simple API call :
```
    var ASINList = [ 'ASIN.1', 'ASIN.2' ];
    var mwsRequestData = {
        Version: '2011-10-01',
        Action: 'GetLowestOfferListingsForASIN',
        SellerId: mwsAccount.sellerId,
        MarketplaceId: mwsAccount.marketplaceId,
        ItemCondition: 'New'
    };
    try {
        var index = 1;
        for (var i in ASINList) {
            mwsRequestData[ 'ASINList.ASIN.' + index ] = ASINList[ i ];
            index++;
        }
        var response = await amazonMws.products.searchFor(mwsRequestData);
        console.log('response ', response);
    } catch (error) {
        console.log('error products', error);
    }
```
