### ISSUE TITLE
ListMarketplaceParticipations function NextToken response

### ISSUE THREAD

**Issue by bahadirkadak** [bhushankumarl/amazon-mws#133]
Hi ,
use ListMarketplaceParticipations function and Amazon MWS documentation says that function return NextToken value but I can't see this prop;
    amazonMws.sellers.search({
        'Version': '2011-07-01',
        'Action': 'ListMarketplaceParticipations',
        'SellerId': sellerID,
        'MWSAuthToken': mwsAuthToken
    }, function (error, response) {
        if (error) {
            console.log('error products', error);
            return;
        }
        console.log('response metadata ', response);
    });

Response:

 { ListParticipations: 
   { Participation: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  ListMarketplaces: 
   { Marketplace: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] },
  ResponseMetadata: { RequestId: '12263109-2666-49aa-b361-53c4d82fe9a8' },
  Headers: 
   { 'x-mws-quota-max': 'unknown',
     'x-mws-quota-remaining': 'unknown',
     'x-mws-quota-resetson': 'unknown',
     'x-mws-timestamp': '2020-04-21T17:39:31.351Z',
     'content-type': 'text/xml',
     'content-charset': 'unknown',
     'content-length': '4935',
     'content-md5': 'unknown',
     date: 'Tue, 21 Apr 2020 17:39:31 GMT' },
  StatusCode: 200 }

**Comment by bhushankumarl** [comment]
@bahadirkadak 

```
    amazonMws.sellers.search({
        'Version': '2011-07-01',
        'Action': 'ListMarketplaceParticipations',
        'SellerId': awsSellerAccount.SellerId,
        'MWSAuthToken': awsSellerAccount.MWSAuthToken
    }, function (error, response) {
        if (error) {
            console.log('error ', error);
            return;
        }
        console.log('response', JSON.stringify(response, null, 2));
    });
```

This is working as expected.
Please take a look at the MWS documentation for further help.

https://docs.developer.amazonservices.com/en_US/sellers/Sellers_ListMarketplaceParticipations.html
