### ISSUE TITLE
GetEligibleShippingServices Return GenericError

### ISSUE THREAD

**Issue by tianmei1** [bhushankumarl/amazon-mws#134]
OriginalError:
   { Type: 'Sender',
     Code: 'MalformedInput',
     Message: 'boolean must follow xsd1.1 definition' },
  Headers:
   { 'x-mws-quota-max': 'unknown',
     'x-mws-quota-remaining': 'unknown',
     'x-mws-quota-resetson': 'unknown',
     'x-mws-timestamp': '2020-05-06T14:26:19.439Z',
     'content-type': 'text/xml',
     'content-charset': 'unknown',
     'content-length': '325',
     'content-md5': 'unknown',
     date: 'Wed, 06 May 2020 14:26:19 GMT' }

**Comment by bhushankumarl** [comment]
@tianmei1 
Can you share the code sample over here?
Have you tried the request from Amazon Scratchpad, is that working fine?

**Comment by bhushankumarl** [comment]
@tianmei1 
It seems working perfectly.

From your error, it looks like you are not passing the boolean value in the correct way. Please feel free to add your request sample here.
