### ISSUE TITLE
Error in parsing to json

### ISSUE THREAD

**Issue by AmichayMiara** [bhushankumarl/amazon-mws#137]
Hi,

returns report (_GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE_)

The report work fine via scratchpad.
When using amazon-mws one of the items is having a shift with the fields values.

![2020-05-25 17_54_42-pma-website  C__Users_michi_WebstormProjects_pma-website  -  _functions_src_co](https://user-images.githubusercontent.com/44358624/82824670-668b6480-9eb2-11ea-910b-41735781ef7e.png)

Tracking ID value should be 795865350928
...
Return quantity is the Item Name instead of '1'.

__________________
Maybe there is a white space after the "FedEx" string that cause a bug with parsing to json

**Comment by AmichayMiara** [comment]
example tsv
from scratchpad output.

one example of a good item
and the bad one (order id 112-9839305-4540205)
[amazon.txt](https://github.com/bhushankumarl/amazon-mws/files/4677912/amazon.txt)

**Comment by bhushankumarl** [comment]
@AmichayMiara 
I'll check and get back to you.

**Comment by AmichayMiara** [comment]
@bhushankumarl 
Thank you, but please hold your check.

We think that it is Amazon's formatting problem.
Their developer team on it.

**Comment by bhushankumarl** [comment]
@AmichayMiara 
Sure.

If you are looking for the Amazon MWS developer, please feel free to set a meeting with our experts. https://calendly.com/bhushankumar/project-consultation
