### ISSUE TITLE
How to handle Amazon throttling

### ISSUE THREAD

**Issue by abhishekj** [bhushankumarl/amazon-mws#15]
Hello,
I have observed we do not get the headers in the response of Amazon using this API. This means i cannt handle throttling since the info is not passed, and i think the library itself dont handle it. 

Please tell me how to get the headers or how to handle it.

thanks

**Comment by bhushankumarl** [comment]
Hello,

Send me the following detail.
- Which API are you using, send the copy of that function?
- Which response are you found, send the response of copy?
- Which amazon-mws version are you using?

Thanks

**Comment by abhishekj** [comment]
Hi,

 

We are getting throttling header for GetReportList request. but no header info For GetReport request which is our main concern.

 

 

Function 1 : amazonMws.reports.search({

        'Version': '2009-01-01',

        'Action': 'GetReport',

        'SellerId': 'SELLER_ID',

        'MWSAuthToken': 'MWS_AUTH_TOKEN',

        'ReportId':'REPORT_ID'

    }, function (error, response) {

        if (error) {

            console.log('error ', error);

            return;

        }

        console.log('response', response);

    });

 

Function 2: amazonMws.reports.search({

        'Version': '2009-01-01',

        'Action': 'GetReportList',

        'SellerId': 'SELLER_ID',

        'MWSAuthToken': 'MWS_AUTH_TOKEN',

        //'ReportTypeList.Type.1': 'REPORT_TYPE_LIST' //optional

    }, function (error, response) {

        if (error) {

            console.log('error ', error);

            return;

        }

        console.log('response', response);

    });

'Version': '2009-01-01'

 

Let me know if you need the response, which I get, I can send that offline , as it is my specific info,

thanks

Abhishek Jain 

+91 9971376767

**Comment by bhushankumarl** [comment]
The throttling detail in non-xml APIs has been added into amazon-mws@0.0.15 . Take the latest update and verify it. @abhishekj
