### ISSUE TITLE
JSON output isn't in the expected JSON format.

### ISSUE THREAD

**Issue by igauravsehrawat** [bhushankumarl/amazon-mws#2]
I see, you are using `xml2json` but the JSON output isn't most appealing and easy to use.

For eg:
I get the response like below
`
[ { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '  <ListInventorySupplyResult>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '    <MarketplaceId>MarketplaceId</MarketplaceId>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '    <InventorySupplyList>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '      <member>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <Condition>NewItem</Condition>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <SupplyDetail/>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <TotalSupplyQuantity>1447</TotalSupplyQuantity>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <EarliestAvailability>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '          <TimepointType>Immediately</TimepointType>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        </EarliestAvailability>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <FNSKU>FNSKU</FNSKU>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <InStockSupplyQuantity>147</InStockSupplyQuantity>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <ASIN>ASIN</ASIN>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '        <SellerSKU>SellerSKU</SellerSKU>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '      </member>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '    </InventorySupplyList>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '  </ListInventorySupplyResult>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '  <ResponseMetadata>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '    <RequestId>5ome-24ndom-id</RequestId>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '  </ResponseMetadata>' },
  { '<ListInventorySupplyResponse xmlns="http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/">': '</ListInventorySupplyResponse>' } ]
`

While expected format is:

`{"ListInventorySupplyResponse":{"xmlns":"http://mws.amazonaws.com/FulfillmentInventory/2010-10-01/","ListInventorySupplyResult":{"MarketplaceId":"MarketplaceId","InventorySupplyList":{"member":{"Condition":"NewItem","SupplyDetail":{},"TotalSupplyQuantity":"1447","EarliestAvailability":{"TimepointType":"Immediately"},"FNSKU":"FNSKU","InStockSupplyQuantity":"1447","ASIN":"ASIN","SellerSKU":"SellerSKU"}}},"ResponseMetadata":{"RequestId":"5ome-24ndom-id"}}}'`
`

Is this fine and expected result?

Thanks

**Comment by bhushankumarl** [comment]
@igauravsehrawat 
I have made some changes to fix it.
Would you please take the latest version and verify it?

**Comment by igauravsehrawat** [comment]
What a treat, thank you so much.
Works good for the functionalities provided.

On digging deep, I found out it doesn't have functionalities for [FulfillmentOutboundShipment](http://docs.developer.amazonservices.com/en_US/fba_outbound/FBAOutbound_Overview.html). Not sure if it is within the scope of the package.

Thanks Again.

**Comment by bhushankumarl** [comment]
Yes, It is in our roadmap/ We'll be going to add that soon.

**Comment by igauravsehrawat** [comment]
Awesome, great.

Thanks
