### ISSUE TITLE
fail to load more than 100 inventory (SignatureDoesNotMatch error)

### ISSUE THREAD

**Issue by wewework** [bhushankumarl/amazon-mws#21]
Dear Bhushankumar,

I tried this example below with some codes changed,

https://github.com/bhushankumarl/amazon-mws/blob/master/examples/javaScript/fulfillmentInventory/listInventorySupply.js

We have 160+ ASINs in our store,  but I was only able to fetch 100 of them before getting an error.

below is the code, please can you help check?

//----------------------code starts-----------------------------

var auth = require("./auth");
var amazonMws = require('amazon-mws')(auth.accessKey,auth.secretKey);

var  query = {
    'Version': '2010-10-01',
    'Action': 'ListInventorySupply',
    'SellerId': auth.sellerID,
    'MWSAuthToken': auth.token,
    'MarketplaceId': auth.marketplaceID,
    'QueryStartDateTime': new Date(01, 04, 2018)
}

var nextQuery = {
	
	'SellerId': auth.sellerID,
	'MarketplaceId': auth.marketplaceID,
	'Version': '2010-10-01',
	"AWSAccessKeyId": auth.token,
	'MWSAuthToken': auth.token,
	'Path': "/FulfillmentInventory/2010-10-01"

}

function listInventory(query){

	amazonMws.fulfillmentInventory.search(query, function (error, response) {
	    if (error) {

	    	console.log(nextQuery);

	        console.log('error ', error);
	        return;
	    }else{

	    	// console.log(response);

	    	var members = response.InventorySupplyList.member;

	    	console.log("------------------------------");
	    	console.log(members.length);
	    	console.log("------------------------------");

	    	for (var i = members.length - 1; i >= 0; i--) {
	    		console.log(members[i]);
	    	}

	    	try{

				var nextToken = response.NextToken;

				console.log("------------------------------");

				console.log(nextToken);

				console.log("------------------------------");

				nextQuery["NextToken"] = nextToken;
				nextQuery["Action"] = "ListInventorySupplyByNextToken";

				listInventory(nextQuery);

			}catch(e){

				console.log("All Fetched.");
			}

	    }
	    
	});

}

listInventory(query);

//----------------------code ends-----------------------------

and here is the error msg I get:

error  { Type: 'Sender',
  Code: 'SignatureDoesNotMatch',
  Message: 'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.',

I appreciate your kind attention to this issue. Thank you so very much!

**Comment by bhushankumarl** [comment]
@wewework 
If you look at the example properly. You will found that 'Path' parameter is not required. 
That's the reason you are facing an error on 'nextQuery'.
