### ISSUE TITLE
Throttling headers are set to unknown

### ISSUE THREAD

**Issue by moltar** [bhushankumarl/amazon-mws#28]
Not sure if a bug, or expected behaviour. But the headers for throttling always return `unknown` for the GetOrder command.

```
  Headers:
   { 'x-mws-quota-max': 'unknown',
     'x-mws-quota-remaining': 'unknown',
     'x-mws-quota-resetson': 'unknown',
     'x-mws-timestamp': '2018-06-06T17:57:30.568Z' } }
```

**Comment by moltar** [comment]
While always returning `unknown` for the header value, eventually the requests got throttled and now the promises get rejected. So, I think the library is not reading the headers correctly. Maybe it is the case issue?

**Comment by moltar** [comment]
Request fails with:

```
{ Type: {},
  Code: 'RequestThrottled',
  Message: 'Request is throttled',
  RequestId: 'a880599c-6a60-42a1-8966-8c04e9d10b40' }
```

Which would also benefit from header info, in order to backoff properly.

**Comment by bhushankumarl** [comment]
@moltar 
It is expected behavior. As Amazon MWS itself not providing Throuwtiling detail in `GetReport` call.
