### ISSUE TITLE
Clarification on LICENSE

### ISSUE THREAD

**Issue by igauravsehrawat** [bhushankumarl/amazon-mws#3]
Generally a license has terms and conditions.

Can you clarify on the LICENSE part? Who can use it and how?

Some resources:
1. https://help.github.com/articles/licensing-a-repository/
2. https://choosealicense.com/
3. https://opensource.guide/legal/#which-open-source-license-is-appropriate-for-my-project

Thanks

**Comment by bhushankumarl** [comment]
It has been added now. @igauravsehrawat

**Comment by igauravsehrawat** [comment]
Thank you.
