### ISSUE TITLE
Amazon MWS returning corrupted chars

### ISSUE THREAD

**Issue by marcospampi** [bhushankumarl/amazon-mws#32]
I noticed that some characters gets corrupted when I use GetReport, these characters should be non-ascii characters like apostrophes and the degree one, indeed when I download the flat file from Seller Central characters are right.
Using hex editor I noticed that these characters are always EF BF BD when using amazon-mws, but they should represent a variety of characters.

This is an example of a GetReport of _GET_FLAT_FILE_ORDERS_DATA_
![amazonmwsissue](https://user-images.githubusercontent.com/25354450/42366568-c89dfe9c-8101-11e8-9683-34b88b0e580b.png)
In this screenshot ship-address-1 should be 'Via del Gesù', other characters are corrupted in this report.
Thanks for your time, this issue apart, this library is awesome.

**Comment by bhushankumarl** [comment]
Thank you, @marcospampi 
Can you provide me received XML string?

**Comment by bhushankumarl** [comment]
@marcospampi I am working on that, I'll update you again soon.

**Comment by marcospampi** [comment]
Hi Bushankumarl,
I got the same issue with node-dbf, the problem could actually be the
encoding from which the program read the response stream, got no way to
test it now,but it is a good hint though.
Going forward to my last issue, actually Amazon could send some xlsx files,
or non-xml nor-flatfile too, the issue could be resolved easily and could
prevent serious issues, response content type check so.
Looking forward.
Il lun 9 lug 2018, 13:23 Bhushankumar L <notifications@github.com> ha
scritto:

**Comment by marcospampi** [comment]
As of https://docs.developer.amazonservices.com/en_US/dev_guide/DG_ISO8859.html
The string Amazon returns isn't UTF-8 but ISO8859-1 .
https://www.npmjs.com/package/iconv does the job,

Now this could be solved, another issue happens when amazon send xls files, I'm opening a new issue, and I'll try to help sharing code and thoughts as much I can.
this if from line 211 of AmazonMwsResource.js:

> 

return function (res) {
            var responseString = '';

            let dbgResponseBuffer = [];
            //res.setEncoding('latin1');
            res.on('data', function (chunk) {
                dbgResponseBuffer.push(chunk);
            });
            res.on('end', function () {
                let buf = Buffer.concat(dbgResponseBuffer);
                const writeFileSync = require('fs').writeFileSync;
                var iconv = new Iconv('ISO-8859-1','UTF-8');
                writeFileSync('buffer.bin',iconv.convert(buf)); // got the right output, no corrupted string

**Comment by bhushankumarl** [comment]
@marcospampi Great

**Comment by bhushankumarl** [comment]
@marcospampi 
A new version has been released. Kindly, upgrade to new version.
