### ISSUE TITLE
Not compatible on Lambda Node.js 8.10

### ISSUE THREAD

**Issue by harleyguru** [bhushankumarl/amazon-mws#33]
I have one lambda node.js 8.10 function of importing just this module.
But it gets module initialization error on Lambda.

This issue needs to be fixed ASAP.

Here are some details:
```
'use strict';

var mws = require('amazon-mws')(process.env.ACCESS_KEY_ID, process.env.SECRET_ACCESS_KEY);

module.exports.handler = async event => {
    console.log(JSON.stringify(event));

    return;
};
```
Of course, I am setting environment variables correctly and cofirmed.
This simple code will get error on Lambda.

I attached CloudWatch log for this lambda function.
![screen shot 2018-07-11 at 7 24 01 pm](https://user-images.githubusercontent.com/35247645/42586127-0659bae0-8540-11e8-8503-283933d6899b.png)

**Comment by harleyguru** [comment]
btw, this is working well on my local machine(macOS 10.13.1) and I've confirmed.
But when we deploy it on Lambda, it's not working.

**Comment by bhushankumarl** [comment]
@harleyguru 
Kindly debug it on Lambda whether this value is coming or not `process.env.ACCESS_KEY_ID` and `process.env.SECRET_ACCESS_KEY`.
This should come during intiatlization of the 
```
consoel.log('process.env.ACCESS_KEY_ID, process.env.SECRET_ACCESS_KEY' , process.env.ACCESS_KEY_ID, process.env.SECRET_ACCESS_KEY);
var mws = require('amazon-mws')(process.env.ACCESS_KEY_ID, process.env.SECRET_ACCESS_KEY);
```

**Comment by harleyguru** [comment]
Oh @bhushankumarl Thanks for your suggestion,
I will try and find the problem.

**Comment by harleyguru** [comment]
@bhushankumarl , this is the issue with this module itself. 
I am getting correct passed env values on Lambda function.
This is really weird issue...
Please help me.

**Comment by harleyguru** [comment]
@bhushankumarl 

```
console.log(process.env.ACCESS_KEY_ID);
console.log(process.env.SECRET_ACCESS_KEY);
var MWS = require('amazon-mws');
module.exports.handler = async event => {
    console.log(JSON.stringify(event));

    return;
}
```
I deploy my Lambda function with only this simple code.
I just tried to import only amazon-mws module.
But getting same error on Lambda...

```
START RequestId: 2d9e9eef-157a-497a-95f0-e579d83b0206 Version: $LATEST
module initialization error: Error
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/var/task/functions/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/var/task/functions/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
END RequestId: 2d9e9eef-157a-497a-95f0-e579d83b0206
REPORT RequestId: 2d9e9eef-157a-497a-95f0-e579d83b0206  Duration: 96.89 ms      Billed Duration: 100 ms         Memory Size: 128 MBMax Memory Used: 22 MB
```
This is the error I am getting.
It seems node-expat&node-gyp sub-modules have some issues.
You don't see this error on Lambda?

**Comment by raymatos** [comment]
What was the solution here?

**Comment by harleyguru** [comment]
@raymatos 
node-expat & node-gyp modules were native packages deeply related with running OS.
That means you need to install them on the acctually deployed OS environment.

In my case, I deploy and run my app on Lambda.
The solution is to dockerize.

**Comment by raymatos** [comment]
Can you post your dockerfile?
