### ISSUE TITLE
GetFeedSubmissionResult fails

### ISSUE THREAD

**Issue by marcospampi** [bhushankumarl/amazon-mws#34]
I got GetFeedSubmissionResult to fail, with the error log attached.
[log.txt](https://github.com/bhushankumarl/amazon-mws/files/2189375/log.txt)
That's the code I'm using
`public async GetFeedSubmissionResult<T>(FeedSubmissionId: string, amcli = this.amcli): Promise<T> {
        try {
            const res: T = await amcli.feeds.search(this.BuildRequest({ FeedSubmissionId: FeedSubmissionId }, "GetFeedSubmissionResult"));
            return res;
        }
        catch (e) {
            throw e;
        }
    }
`
this.BuildRequest(args,action) makes sure all the parameters are setup like that before I call amcli.feeds.search which is amazon-mws:
`{ FeedSubmissionId: 'xxxxxxxxxxxx',
  Version: '2009-01-01',
  Action: 'GetFeedSubmissionResult',
  SellerId: 'xxxxxxxxxxxx',
  MWSAuthToken: 'xxxxxxxxxxxx',
  'MarketplaceIdList.Id.1': 'xxxxxxxxxxxx' }`

**Comment by bhushankumarl** [comment]
@marcospampi 
The example you are using looks different from the library. Kindly check example for this section https://github.com/bhushankumarl/amazon-mws/tree/master/examples/javaScript and use it accordingly.

**Comment by marcospampi** [comment]
Still get this error: i've got the file output of the response from amazon on AmazonMwsResource.js line 199, where it says that's not xml, using writeFileSync:
the file that amazon send should be xlsx, or at least using `file $filename` on linux tells me that the response is Microsoft OOXML, though it is corrupted in some way.
It is strange that the Submission was a _POST_FLAT_FILE_LISTINGS_DATA_ and the get result is kinda of xlsx, I sent the submission long ago by seller central though.

**Comment by bhushankumarl** [comment]
@marcospampi 
A new version has been released. Kindly, upgrade to new version.
