### ISSUE TITLE
listOrders lists wrong timeframe

### ISSUE THREAD

**Issue by chdoub** [bhushankumarl/amazon-mws#41]
I'm trying to request amazon orders with your listOrders example. I want to request orders with the parameter CreatedAfter. After changing this parameter in your function call, the call seems to ignore 'After' and always responses with the 'Before' parameters. It's similar with LastUpdateAfter and Before parameter.

How can we solve this issue?

**Comment by bhushankumarl** [comment]
@chdoub 
Can you share a sample that you are using to query data?

**Comment by chdoub** [comment]
your sample listOrders.js with parameters LastUpdatedAfter or CreatedAfter ... both params seem to list -before as filter

`'use strict';

var accessKey = process.env.AWS_ACCESS_KEY_ID || 'YOUR_KEY';
var accessSecret = process.env.AWS_SECRET_ACCESS_KEY || 'YOUR_SECRET';

var amazonMws = require('../../../lib/amazon-mws')(accessKey, accessSecret);

var orderRequest = function () {
    amazonMws.orders.search({
        'Version': '2013-09-01',
        'Action': 'ListOrders',
        'SellerId': 'SELLER_ID',
        'MWSAuthToken': 'MWS_AUTH_TOKEN',
        'MarketplaceId.Id.1': 'MARKET_PLEACE_ID_1',
        'CreatedAfter': new Date(14, 8, 2018)
    }, function (error, response) {
        if (error) {
            console.log('error ', error);
            return;
        }
        console.log('response', response);
    });
};

orderRequest();`

**Comment by EnSomHodder** [comment]
I am having the same issue. Try to list orders updated after a specific date, ex. 2018 July 1st. However, in the real request sent to MWS, "lastUpdatedAfter" parameter is set to 1970-xxxx, which seems the default value.

**Comment by bhushankumarl** [comment]
Please check for your date construction. https://www.w3schools.com/js/js_dates.asp
@EnSomHodder @chdoub
