### ISSUE TITLE
Illegal character sequence in iconv while fetching 'GetFeedSubmissionResult'

### ISSUE THREAD

**Issue by vishalbhaliya94** [bhushankumarl/amazon-mws#48]
Hello,

i'm facing an error like Illegal character sequence in iconv while fetching 'GetFeedSubmissionResult'.

Please give suggestions to solve it.

**Comment by bhushankumarl** [comment]
@vishalbhaliya94 
Can you share a sample that you are using to query data?

**Comment by bhushankumarl** [comment]
@vishalbhaliya94 It's working fine as per expectation. Please check for API call.

**Comment by vishalbhaliya94** [comment]
this.amazonAWS.feeds.search({
        'Version': '2009-01-01',
        'Action': 'GetFeedSubmissionResult',
        'SellerId': AWS.AWS_SELLER_ID,
        'MWSAuthToken': AWS.AWS_ACCESS_TOKEN,
        'FeedSubmissionId': FeedSubmissionId
      })

**Comment by vishalbhaliya94** [comment]
@bhushankumarl Nope. Request is correct but i haven't submit any feed yet. So you need to work for Listing all SubmissionList and using SubmissionId we can fetch result of it. because it can not convert response of MWS.

**Comment by marcospampi** [comment]
@vishalbhaliya94  can you try to use the `__RAW__` option like this:
[https://github.com/bhushankumarl/amazon-mws/blob/master/examples/javaScript/feeds/getFeedSubmissionResultRaw.js](url)
