### ISSUE TITLE
How to handle throttling

### ISSUE THREAD

**Issue by moltar** [bhushankumarl/amazon-mws#5]
http://docs.developer.amazonservices.com/en_CA/dev_guide/DG_Throttling.html

API returns the following headers:

```
x-mws-quota-max: 3600
x-mws-quota-remaining: 10
x-mws-quota-resetsOn: Wed, 06 Mar 2013 19:07:58 GMT
```

Is it possible to expose these somehow?

Thanks.

**Comment by bhushankumarl** [comment]
@moltar 
Yes, it is possible and I had added the details.
Now you can get details in response fo every API. Let me know if it does work for you or not. 

```json
{ 
  "x-mws-quota-max": "60.0",
  "x-mws-quota-remaining": "38.0",
  "x-mws-quota-resetson": "2017-12-08T08:21:00.000Z",
  "x-mws-timestamp": "2017-12-08T07:52:15.567Z"
}
```

**Comment by moltar** [comment]
Thank you for the quick response!
