### ISSUE TITLE
Breaking change with v0.0.19, `ASIN` and `status` fields removed from root of results

### ISSUE THREAD

**Issue by colinskow** [bhushankumarl/amazon-mws#50]
This is an example from `GetMyPriceForASIN`, but I believe the same change applies to all product info operations. A couple fields were removed from the results.

```json
[
  {
    "ASIN": "B01BICBEQ2", // <-- NO LONGER PRESENT
    "status": "Success",  // <-- NO LONGER PRESENT
    "Product": {
      "Identifiers": {
        "MarketplaceASIN": {
          "MarketplaceId": "A1F83G8C2ARO7P",
          "ASIN": "B01BICBEQ2"
        }
      },
      "Offers": {}
    }
  }
]
```

I've already fixed on my end. Just for your info or others who may have problems after upgrade. Any breaking changes should be noted with a semver major version release.

**Comment by bhushankumarl** [comment]
@colinskow It has been fixed in the `development` branch. It would be helpful if you can validate that.

**Comment by colinskow** [comment]
I changed my code so it grabs `Product.Identifiers.MarketplaceASIN.ASIN` instead. Thank you very much for your help.
