### ISSUE TITLE
MWS 500 server error still crashes Node

### ISSUE THREAD

**Issue by colinskow** [bhushankumarl/amazon-mws#51]
Version 0.0.19. This is from a request to "GetMyFeesEstimate." The request was perfectly formed and this tends to happen randomly once in a few hundred operations. For this it is very hard to reproduce on demand.

Apparently MWS did not set a content-type header with the error response. (502 bad gateway)

```xml
<?xml version="1.0"?>
<ErrorResponse>
    <Error>
        <Type>Server</Type>
        <Code>500</Code>
        <Message>500 - Server Error</Message>
        <Detail />
    </Error>
</ErrorResponse>
```

```
/app/api/node_modules/amazon-mws/lib/AmazonMwsResource.js:211
2018-09-14T22:38:31.732701+00:00 app[worker.1]: if (headers['content-type'].indexOf('charset') > -1 && headers['content-type'].split(';')[0] && headers['content-type'].split(';')[1]) {
TypeError: Cannot read property 'indexOf' of undefined at ClientRequest.<anonymous> (/app/api/node_modules/amazon-mws/lib/AmazonMwsResource.js:211:41)
```

This wouldn't be a big deal, except for some reason it's bypassing my Promise catch handler and crashing the entire app.

**Comment by bhushankumarl** [comment]
@colinskow 
Again I have normalized the condition checking exactly at the mentioned line. But still, I am not able to regenerate the same error.
It has been fixed in the `development` branch. It would be helpful if you can validate that.

**Comment by colinskow** [comment]
I'm trying to think if there is a way to log the full details of the MWS response so you can feed those into a test. If you have access to UK MWS credentials I can give you the exact request parameters that consistently produce the 502 error. I think it's just some edge case that Amazon hasn't handled correctly.

**Comment by bhushankumarl** [comment]
@colinskow I am not able to regenerate this error.

**Comment by bhushankumarl** [comment]
@colinskow  
I have made changes according to it. Can you check against `development` branch?

**Comment by colinskow** [comment]
Here is code to reproduce the error. You'll need amazon.co.uk credentials. The error that appears now is `Invalid JSON received from the AmazonMws API`. I'm not sure what is causing the error, but it appears that certain ASINs crash the system. When I delete a couple items from the request sometimes it works.

Either way we should be able to handle MWS returning errors gracefully without crashing node.

```js
require('dotenv').config();
AmazonMWS = require('amazon-mws');

const mwsMarkets = {
  GB: { code: 'A1F83G8C2ARO7P', url: 'mws-eu.amazonservices.com', currency: 'GBP' }
};

function getMwsInstance(market) {
  const mws = new AmazonMWS(process.env.AWS_ACCESS_KEY_ID, process.env.AWS_SECRET_KEY);
  const host = mwsMarkets[market].url;
  if (!host) {
    throw new Error('invalid market or region');
  }
  mws.setHost(host);
  return mws;
}

function estimateMyFees(feeRequests, market) {
  const amazon = getMwsInstance(market);
  const query = {
    'Version': '2011-10-01',
    'Action': 'GetMyFeesEstimate',
    'SellerId': process.env.AWS_SELLER_ID,
    'MWSAuthToken': process.env.AWS_MWS_AUTH_TOKEN,
    'MarketplaceId': mwsMarkets[market].code
  };
  const prefix = 'FeesEstimateRequestList.FeesEstimateRequest';
  const currency = mwsMarkets[market].currency;
  const queryItems = {};
  feeRequests.forEach((req, i) => {
    queryItems[`${prefix}.${i+1}.MarketplaceId`] = mwsMarkets[market].code;
    queryItems[`${prefix}.${i+1}.IdType`] = 'ASIN';
    queryItems[`${prefix}.${i+1}.IdValue`] = req.asin;
    queryItems[`${prefix}.${i+1}.Identifier`] = req.asin;
    queryItems[`${prefix}.${i+1}.IsAmazonFulfilled`] = req.fba;
    queryItems[`${prefix}.${i+1}.PriceToEstimateFees.ListingPrice.Amount`] = req.price;
    queryItems[`${prefix}.${i+1}.PriceToEstimateFees.ListingPrice.CurrencyCode`] = currency;
    if (req.shipping) {
      queryItems[`${prefix}.${i+1}.PriceToEstimateFees.Shipping.Amount`] = req.shipping;
      queryItems[`${prefix}.${i+1}.PriceToEstimateFees.Shipping.CurrencyCode`] = currency;
    }
  });
  console.log(JSON.stringify({ ...query, ...queryItems }, null, 2));
  return amazon.products.search({...query, ...queryItems});
}

const feeRequests = [
  { asin: 'B07622KXFK',
  price: '27.33',
  shipping: '',
  fba: true },
  { asin: 'B00JFGXBI8',
  price: '61.98',
  shipping: '',
  fba: true },
  { asin: 'B075DPL9GX',
  price: '63.83',
  shipping: '',
  fba: true },
  { asin: 'B01MQSESY4',
  price: '17.93',
  shipping: '1.50',
  fba: true },
  { asin: 'B01BPAU3QO',
  price: '34.88',
  shipping: '',
  fba: true },
  { asin: 'B01HDC57FU',
  price: '75.99',
  shipping: '8.99',
  // shipping: '',
  fba: true },
  { asin: 'B016INTK3U',
  price: '60.99',
  shipping: '8.99',
  // shipping: '',
  fba: true }
];

estimateMyFees(feeRequests, 'GB')
  .then(results => {
    console.log(JSON.stringify(results, null, 2));
  })
  .catch(err => console.error(err));
```

**Comment by bhushankumarl** [comment]
@colinskow 
I was able to reproduce that while using `GetMyFeesEstimate` alone. I have added fixed for it.

**Comment by colinskow** [comment]
Excellent... Thank you very much @bhushankumarl !
Any idea what may be causing it? It seems to me there are just random ASINs which cause MWS to break and return a 500 error.

**Comment by bhushankumarl** [comment]
@colinskow It would be helpful if you check again `development` branch.

**Comment by bhushankumarl** [comment]
@colinskow 
It has been fixed and the version has been released.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.21

Please feel free to reopen if you still found any bug.

**Comment by colinskow** [comment]
Thank you so much for your quick response!
