### ISSUE TITLE
RequestReport is not available

### ISSUE THREAD

**Issue by Kamalkant975** [bhushankumarl/amazon-mws#53]
For this functionality I did apply these changes.
[requestreport.txt](https://github.com/bhushankumarl/amazon-mws/files/2392630/requestreport.txt)

**Comment by bhushankumarl** [comment]
@Kamalkant975 Thank You.

**Comment by smulder** [comment]
do you guys happen to have even a rough quick example of how you were able to make this work? I'd be super appreciative! Thanks, Scott

**Comment by bhushankumarl** [comment]
@smulder 
Well, Examples are here https://github.com/bhushankumarl/amazon-mws/tree/master/examples/javaScript
