### ISSUE TITLE
Breaking Change: keys named "Value" replaced by "_"

### ISSUE THREAD

**Issue by colinskow** [bhushankumarl/amazon-mws#57]
Keys named "Value" have been replaced with "_" in all output. Example from `GetCompetitivePricingForASIN`

Before:
```
 "NumberOfOfferListings": {
          "OfferListingCount": [
            {
              "condition": "New",
              "Value": "21"
            },
            {
              "condition": "Any",
              "Value": "21"
            }
          ]
        }
      }
```

After:
```
"NumberOfOfferListings": {
          "OfferListingCount": [
            {
              "_": "21",
              "condition": "New"
            },
            {
              "_": "11",
              "condition": "Used"
            },
            {
              "_": "32",
              "condition": "Any"
            }
          ]
        }
      }
```

After fixing this, you should record raw XML output from specific MWS API calls and run that through your tests to ensure the JSON output never changes between builds.

**Comment by bhushankumarl** [comment]
@colinskow 
To notify the issue. We try our best to keep the library error-free.
However, the above issue has been fixed on `development` branch, can you please verify and confirm it?
Your help will be highly appreciated.

**Comment by bhushankumarl** [comment]
It has been resolved into the new release. https://www.npmjs.com/package/amazon-mws @colinskow

**Comment by bhushankumarl** [comment]
It has been resolved into the new release. https://www.npmjs.com/package/amazon-mws @colinskow
