### ISSUE TITLE
GetFeedSubmissionResult, 'ErrorResponse' of undefined

### ISSUE THREAD

**Issue by YamanSehzade** [bhushankumarl/amazon-mws#60]
when i use **GetFeedSubmissionResult** action, i get this error.

> C:\amazon-book\server\node_modules\amazon-mws\lib\AmazonMwsResource.js:302
>                         if (response.ErrorResponse) {
>                                      ^
> TypeError: Cannot read property 'ErrorResponse' of undefined
>     at C:\amazon-book\server\node_modules\amazon-mws\lib\AmazonMwsResource.js:302:38
>     at C:\amazon-book\server\node_modules\amazon-mws\lib\AmazonMwsResource.js:204:28
>     at ParserStream.<anonymous> (C:\amazon-book\server\node_modules\amazon-mws\lib\AmazonMwsResource.js:165:26)
>     at emitOne (events.js:116:13)
>     at ParserStream.emit (events.js:211:7)
>     at spreadArgs (C:\amazon-book\server\node_modules\fast-csv\lib\extended.js:43:25)
>     at ParserStream.emit (C:\amazon-book\server\node_modules\fast-csv\lib\parser\parser_stream.js:325:13)
>     at onwriteError (_stream_writable.js:412:12)
>     at onwrite (_stream_writable.js:440:5)
>     at ParserStream.afterTransform (_stream_transform.js:90:3)
>     at C:\amazon-book\server\node_modules\fast-csv\lib\parser\parser_stream.js:223:21
>     at ParserStream._parseLine [as _parse] (C:\amazon-book\server\node_modules\fast-csv\lib\parser\parser_stream.js:196:13)
>     at ParserStream._transform (C:\amazon-book\server\node_modules\fast-csv\lib\parser\parser_stream.js:221:18)
>     at ParserStream.Transform._read (_stream_transform.js:186:10)
>     at ParserStream.Transform._write (_stream_transform.js:174:12)
>     at doWrite (_stream_writable.js:397:12)
>     at writeOrBuffer (_stream_writable.js:383:5)
>     at ParserStream.Writable.write (_stream_writable.js:290:11)
>     at Readable.ondata (_stream_readable.js:639:20)
>     at emitOne (events.js:116:13)
>     at Readable.emit (events.js:211:7)
>     at Readable.read (_stream_readable.js:475:10)

![image](https://user-images.githubusercontent.com/22771125/46486094-52868100-c7fd-11e8-9e74-80c034276f7f.png)

my codes are here;

```
 try {
      var FeedSubmissionId = "50052017808";
      const response = await amazonMws.feeds.search({
        'Version': '2009-01-01',
        'Action': 'GetFeedSubmissionResult',
        'SellerId': SELLER_ID,
        'MWSAuthToken': MWS_AUTH_TOKEN,
        'FeedSubmissionId': FeedSubmissionId
      });

      console.log("RESPONSE:", response);
    } catch (error) {
      console.log("ERROR:", error);
    }
```

**Comment by bhushankumarl** [comment]
@YamanSehzade 
Can you please try with export DEBUG=MWS:* and send me what output comes in?

**Comment by YamanSehzade** [comment]
this work, thanks.

```
  try {
      var FeedSubmissionId = "50052017808";
      const response = await amazonMws.feeds.search({
        'Version': '2009-01-01',
        'Action': 'GetFeedSubmissionResult',
        'SellerId': SELLER_ID,
        'MWSAuthToken': MWS_AUTH_TOKEN,
        'FeedSubmissionId': FeedSubmissionId,
        __RAW__: true
      });

      console.log("RESPONSE:", response);

      if (response.hasOwnProperty('data'))
        console.log(response.data.toString('utf8'));


    } catch (error) {
      console.log("ERROR:", error);
    }
```
