### ISSUE TITLE
Future Request:  Subscriptions 

### ISSUE THREAD

**Issue by YamanSehzade** [bhushankumarl/amazon-mws#62]
hi @bhushankumarl, thank you very much for this library. 
Is it possible to add "Subscription" api ?

**Comment by bhushankumarl** [comment]
@YamanSehzade 
Yes, it's possible to do that. it's in our roadmap.

**Comment by bhushankumarl** [comment]
It has been added to the new release. https://www.npmjs.com/package/amazon-mws @YamanSehzade

**Comment by bhushankumarl** [comment]
It has been added to the new release. https://www.npmjs.com/package/amazon-mws @YamanSehzade
