### ISSUE TITLE
MWS AUTH Token

### ISSUE THREAD

**Issue by skmuzeer** [bhushankumarl/amazon-mws#68]
How to access all the API's through MWS_AUTH_TOKEN without providing access_key and secret_key, as I have studied in amazon document that with out key's you can access the api's with the help of MWS_AUTH_TOKEN

Can you help me out with small example, as i have never seen in you existing code with such functionality as you have already saved the access_key and secret_key. I don't want to use the both

**Comment by marcospampi** [comment]
You can't. You must have misunderstood the documents. Access and secret key are developer's related credentials, wether auth token is seller's token. You cannot use amazon mws without a seller/user token. Should be closed.
