### ISSUE TITLE
Other Amazon MWS Regions e.g. EU - overriding DEFAULT_HOST?

### ISSUE THREAD

**Issue by leotulipan** [bhushankumarl/amazon-mws#69]
How do I properly override line 4 of amazon-mws.js 

AmazonMws.DEFAULT_HOST = 'mws-eu.amazonservices.com';

Other Regions, namely EU (Germany, UK, etc.) need to connect to that host to get their data, otherwise, with the same Secret and MWS Token, we only get a 401 access denied

**Comment by bhushankumarl** [comment]
@leotulipan 
See here: https://github.com/bhushankumarl/amazon-mws/blob/master/examples/javaScript/sample/listOrders.js
