### ISSUE TITLE
MalformedInput

### ISSUE THREAD

**Issue by jinkoo2** [bhushankumarl/amazon-mws#75]
The library works fine for some, including, ListOrders, but when I try to get the product information. I get the following error. I used the example code provided.

<?xml version="1.0"?><ErrorResponse xmlns="http://mws.amazonservices.com/schema/Products/2011-10-01"><Error><Type>Sender</Type><Code>MalformedInput</Code><Message>Start of list found where not expected</Message></Error><RequestId>e8dcf91f-b0f0-481a-b732-0ff53c7dff62</RequestId></ErrorResponse>

**Comment by bhushankumarl** [comment]
@jinkoo2 Kindly send the Request format and response format for further investigation.

**Comment by jinkoo2** [comment]
I tested today, the same code.... and it works fine. Strange... The code is the sample code on the web page 
Thanks!

amazonMws.products.search({
        'Version': '2011-10-01',
        'Action': 'ListMatchingProducts',
        'SellerId': 'SELLER_ID',
        'MWSAuthToken': 'MWS_AUTH_TOKEN',
        'MarketplaceId': 'MARKET_PLACE_ID',
        'Query':'k'
    }, function (error, response) {
        if (error) {
            console.log('error ', error);
            return;
        }
        console.log('response', response);
    });
