### ISSUE TITLE
signature doesn't match

### ISSUE THREAD

**Issue by robot110011** [bhushankumarl/amazon-mws#78]
hi there,

I'm lopping a search report (Report Request List) (to get the generated id when ready) in a setInterval but one the second run (and beyond) I get a message: 

'The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.'

Code:

```
const paramCheckReportStatus = {
        Version: '2009-01-01',
        Action: 'GetReportRequestList',
        SellerId: sellerID,
        MWSAuthToken: 'MWS_AUTH_TOKEN',
        'ReportRequestIdList.Id.1': ReportRequestId,
    };

 setInterval(() => {
        amazonMws.reports.search(paramCheckReportStatus, (error, response) => {
            if (error) {
                console.log('error ', error);
            }
            console.log('response', response);
        });
    }, 5000);
```

What am I missing here?

Thanks

PS: I verified the ReportRequestId and it's correct (I'm first running the submit report and getting the response)

**Comment by bhushankumarl** [comment]
@robot110011 
Your way of looping should be corrected. You can try this package for async looping behaviour http://bluebirdjs.com/docs/api/promise.mapseries.html

**Comment by robot110011** [comment]
Hey there,

Thanks for your reply.
I see that you change the parameters after first check that's why I'm getting signature error. It's clearly my fault. I switch to async functions and works fine now. Thank you!
