### ISSUE TITLE
Subscriptions in typescript definitions

### ISSUE THREAD

**Issue by lohiaad** [bhushankumarl/amazon-mws#79]
Great library.
can you please add Subscriptions in type defs. 

`

declare class AmazonMWS {

    constructor()

    constructor(key: string, token: string);

    setApiKey(key: string, secret: string): void;

    setHost(host?: string, port?: string, protocol?: string): void;

    feeds: Feeds;

    finances: Finances;

    fulfillmentInboundShipment: FulfillmentInboundShipment;

    fulfillmentInventory: FulfillmentInventory;

    fulfillmentOutboundShipment: FulfillmentOutboundShipment;

    merchantFulfillment: MerchantFulfillment;

    orders: Orders;

    products: Products;

    reports: Reports;

    sellers: Sellers;

}

`

**Comment by bhushankumarl** [comment]
@lohiaad 
Corrected in #76

**Comment by bhushankumarl** [comment]
@lohiaad 
The new version has been released with a fixed and new feature.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.24
