### ISSUE TITLE
Get the listing product with Report

### ISSUE THREAD

**Issue by foch01** [bhushankumarl/amazon-mws#80]
Hello,

I can not retrieve a report of all products from a sellercentral account with this method:

```
    var ReportRequestId = '10101010XXX';
    amazonMws.reports.search({
        'Version': '2009-01-01',
        'Action': 'GetReportRequestList',
        'SellerId': 'SELLER_ID',
        'MWSAuthToken': 'MWS_AUTH_TOKEN',
        'ReportRequestIdList.Id.1': ReportRequestId
    }, function (error, response) {
        if (error) {
            console.log('error ', error);
            return;
        }
        console.log('response', response);
    });  
```

It returns to me this:

```
"HasNext": "false",
         "ReportRequestInfo": {
             "ReportType": "_GET_MERCHANT_LISTINGS_ALL_DATA_",
                 "ReportProcessingStatus": "_SUBMITTED_",
                 "EndDate": "2019-03-26T09:16:33+00:00",
                 "Scheduled": "false",
                 "ReportRequestId": "64163017981",
                 "SubmittedDate": "2019-03-26T09:16:33+00:00",
                 "StartDate": "2019-03-26T09:16:33+00:00"
             },
     "ResponseMetadata": {
             "RequestId": "d2cab60e-30a5-47d1-8555-248c313bb0a6"
             },
     "Headers": {...},
"StatusCode": 200
}
```

I do not have the ReportId in the request response

That should have returned to me this:
```
<GetReportListResponse xmlns="http://mws.amazonaws.com/doc/2009-01-01/">
  <GetReportListResult>
    <HasNext>false</HasNext>
    <ReportInfo>
      <ReportType>_GET_MERCHANT_LISTINGS_ALL_DATA_</ReportType>
      <Acknowledged>false</Acknowledged>
      <ReportId>15521486795017981</ReportId>
      <ReportRequestId>64163017981</ReportRequestId>
      <AvailableDate>2019-03-26T09:16:44+00:00</AvailableDate>
    </ReportInfo>
  </GetReportListResult>
  <ResponseMetadata>
    <RequestId>03e99980-121c-4df9-a69c-58eb4c606094</RequestId>
  </ResponseMetadata>
</GetReportListResponse>
```

**Comment by foch01** [comment]
Up ?

**Comment by bhushankumarl** [comment]
@foch01 
#76 Added feature to allow a user to change response type into XML format.

**Comment by foch01** [comment]
It can not be done in JSON format?

**Comment by bhushankumarl** [comment]
It can be in both XML as well as JSON.

**Comment by bhushankumarl** [comment]
@foch01 
The new version has been released with a fixed and new feature.
https://github.com/bhushankumarl/amazon-mws/releases/tag/v0.0.24

**Comment by foch01** [comment]
Yes I understand but I want to do this : https://help.godatafeed.com/hc/en-us/articles/360000192092-Amazon-Get-product-catalog-using-Amazon-MWS-Scratchpad


And it is impossible to recover the report id in my answer.

Whereas with the scratchpad it works well

**Comment by foch01** [comment]
It's not possible to get this response correctly in JSON ?

**Comment by bhushankumarl** [comment]
@foch01 
You have to wait until the submitted report has been processed. Then after you can have the `reportId`.

- It's possible in both JSON as well as XML format.

Reference : 
http://docs.developer.amazonservices.com/en_IN/reports/Reports_Overview.html

**Comment by foch01** [comment]
I have to wait how long?

Because when I do exactly the same manipulation on the scratchpad it's immediate

**Comment by bhushankumarl** [comment]
@foch01 
Correct.

**Comment by foch01** [comment]
I have to wait how long?
