### ISSUE TITLE
GetMatchingProductForID

### ISSUE THREAD

**Issue by mixmasterjt** [bhushankumarl/amazon-mws#81]
I am interested in submitting a list of 20 ASINS to the GetMatchingProductForID.  

I see a list is supported for "GetMatchingProduct" but is it possible to submit a list of ASINS for "GetMatchingProductForID"?

**Comment by bhushankumarl** [comment]
@mixmasterjt 
Please refer to the http://docs.developer.amazonservices.com/en_IN/dev_guide/DG_IfNew.html .
This library only supports which has been provided by the AWS MWS.
