### ISSUE TITLE
charset error

### ISSUE THREAD

**Issue by robot110011** [bhushankumarl/amazon-mws#82]
Hi there,

I'm getting wrong string from Amazon when there's an umlaut chars like ü. It gets translated to �. I've already tried to convert using Iconv but it seems the string isn't coming as ISO 8859-1. Can you please let me know if you change the charset after getting the data from MWS?

Thanks

**Comment by bhushankumarl** [comment]
@robot110011 
Please check this example.

https://github.com/bhushankumarl/amazon-mws/blob/master/examples/javaScript/feeds/getFeedSubmissionResultCharset.js

**Comment by robot110011** [comment]
Perfect, now it works!! Thanks for your quick reply
