### ISSUE TITLE
listorders with another timezone

### ISSUE THREAD

**Issue by robot110011** [bhushankumarl/amazon-mws#85]
Hi there,

Is it possible to request a list orders using the Amazon timezone (PDT)? I know the request is made using UTC and I know I can convert it but it will save time and resources if I could request directly in PDT. I was able to do this using the Amazon PHP API but couldn't using your API.

Here's what I tried:

```
amazonMws.orders.search({
            'Version': '2013-09-01',
            'Action': 'ListOrders',
            'SellerId': 'XXXXXXXXXXXXXX',
            'MWSAuthToken': 'MWS_AUTH_TOKEN',
            'MarketplaceId.Id.1': 'ATVPDKIKX0DER',
            'CreatedAfter': new Date('2019-04-02T16:00:21.784PDT'),
        });
```

**Comment by roasted-toast** [comment]
`'CreatedAfter': '2019-04-02T16:00:21.784PDT',` should work. Does it?

**Comment by robot110011** [comment]
@roasted-toast have you tried it? because with me I got MalformedInput

**Comment by roasted-toast** [comment]
@robot110011 You should probably try removing the milliseconds.

**Comment by robot110011** [comment]
I also tried removing the ms, it seems I really need to request in UTC :(
