### ISSUE TITLE
List Orders By NextToken

### ISSUE THREAD

**Issue by roasted-toast** [bhushankumarl/amazon-mws#86]
I'm just wondering what would be the best approach to get orders from a entire year ?
I can get the proper NextToken value after the first request, but then Amazon returns a 503 response on the 2nd one:

`error  { Type: {},
  Code: 'RequestThrottled',
  Message: 'Request is throttled',
  Headers:
   { 'x-mws-quota-max': 'unknown',
     'x-mws-quota-remaining': 'unknown',
     'x-mws-quota-resetson': 'unknown',
     'x-mws-timestamp': '2019-04-17T10:10:30.346Z',
     'content-type': 'text/xml',
     'content-charset': 'unknown',
     'content-length': '291',
     'content-md5': 'unknown',
     date: 'Wed, 17 Apr 2019 10:10:30 GMT' },
  StatusCode: 503,
  RequestId: 'a2b3a66e-c97c-4a0b-ba6f-deae85410aa0' }
`
I couldn't find any example regarding this issue. Do I have to use a loop ? A time out ?
Thanks !

**Comment by bhushankumarl** [comment]
@roasted-toast 
http://docs.developer.amazonservices.com/en_CA/dev_guide/DG_Throttling.html
Please take a visit on this. It will help you to understand the error and proper solution for that.

**Comment by roasted-toast** [comment]
@bhushankumarl 
We have a large a mount of orders for 2018 (over 40k). I've finally decided to call for a report instead. 

Less time consuming than using the Order API (that is useful for a < 100 orders request) since ListOrder and ListOrderByNextToken share a maximum request quota of six and a restore rate of one request every minute...

Thanks for the tip anyways!

**Comment by lincolnaleixo** [comment]
@egdavid Can I ask you what type of report you were able to request this amount of orders? I'm facing similar issue. Thanks

**Comment by egdavid** [comment]
@lincolnaleixo I know I've used the Amazon MWS Report API to get orders: https://docs.developer.amazonservices.com/en_ES/reports/Reports_WorkingWithOrderReports.html
