### ISSUE TITLE
Not working in all global regions, need input for MWS region

### ISSUE THREAD

**Issue by fernlop** [bhushankumarl/amazon-mws#87]
Im connecting to a developer / seller account in germany and i received an access denied response. 

I fixed it by changing the host from mws.amazonservices.com to mws.amazonservices.de

**Comment by bhushankumarl** [comment]
@fernlop 
https://github.com/bhushankumarl/amazon-mws/blob/master/examples/javaScript/sample/listOrders.js
Here is the example for setting up the host.

**Comment by EGimenoS** [comment]
Hello, the file with the example is not available and I'm having the same problem with the `GetCompetitivePricingForASIN`

currently I'm setting the marketplaceId as stated in the docs for this request:

```
const amazonMws = require("amazon-mws")(awsAccessKeyId, awsSecretAccessKey);
const mwsRequestConfig = {
  Version: "2011-10-01",
  Action: "GetCompetitivePricingForASIN",
  SellerId: sellerId,
  MWSAuthToken: developerId,
  MarketplaceId: marketplaceId,
};

And I am getting this error:

```
[Error] {
  Type: 'AmazonMwsAPIError',
  Code: 'GenericError',
  Message: 'Access denied',
  StatusCode: 401,
  OriginalError: { Type: 'Sender', Code: 'AccessDenied', Message: 'Access denied' },
  Headers: {
    'x-mws-quota-max': 'unknown',
    'x-mws-quota-remaining': 'unknown',
    'x-mws-quota-resetson': 'unknown',
    'x-mws-timestamp': '2020-11-20T14:59:15.326Z',
    'content-type': 'text/xml',
    'content-charset': 'unknown',
    'content-length': '294',
    'content-md5': 'unknown',
    date: 'Fri, 20 Nov 2020 14:59:15 GMT'
  },
  RequestId: '5c7e75e1-696f-457d-9712-4e15448fe697'
}
