### ISSUE TITLE
Products.searchFor method not working

### ISSUE THREAD

**Issue by lounsbrough** [bhushankumarl/amazon-mws#89]
When I make a request to `amazonMws.products.searchFor(options)` with the following `options`:

{ Version: '2011-10-01',
  Action: 'GetMyFeesEstimate',
  SellerId: 'redacted seller id',
  MWSAuthToken: 'redacted auth token',
  'FeesEstimateRequestList.FeesEstimateRequest.1.MarketplaceId': 'ATVPDKIKX0DER',
  'FeesEstimateRequestList.FeesEstimateRequest.1.IdType': 'ASIN',
  'FeesEstimateRequestList.FeesEstimateRequest.1.IdValue': 'B00EWBZ9H2',
  'FeesEstimateRequestList.FeesEstimateRequest.1.IsAmazonFulfilled': 'true',
  'FeesEstimateRequestList.FeesEstimateRequest.1.Identifier': 'request1',
  'FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.CurrencyCode': 'USD',
  'FeesEstimateRequestList.FeesEstimateRequest.1.PriceToEstimateFees.ListingPrice.Amount': '100'}

I get a 500 server error. Please advise if anyone is able to run a similar request successfully.

**Comment by bhushankumarl** [comment]
@lounsbrough 
Can you send me a sample of request with ASIN and their relevant values?
You can use mine email: bhushankumar.lilapara@gmail.com if it can't be put down publicly.

**Comment by lounsbrough** [comment]
I ended up using C# for this project.

**Comment by bhushankumarl** [comment]
@lounsbrough 
Cool.

However, The call that you have used is wrong. It should be like :
```
amazonMws.products.search(options)
```
