### ISSUE TITLE
How to apply for mws developer ID?

### ISSUE THREAD

**Issue by willianwong** [bhushankumarl/amazon-mws#90]
Have you applied for the mws developer ID recently?
After I applied, I waited for 40 days, Amazon told me that I was not qualified, and told me that I needed to learn Acceptable Use Policy and Data Protection Policy.

Can you provide help?
thank you very much!

**Comment by bhushankumarl** [comment]
@willianwong 
This library is aimed to provide only for the API calls. You can check some details on their form.
https://sellercentral.amazon.in/forums/t/registering-developer-for-mws-access/163081
Maybe this can help you.
