### ISSUE TITLE
offAmazonPayments >> SetOrderReferenceDetails

### ISSUE THREAD

**Issue by hiren-ganatra** [bhushankumarl/amazon-mws#92]
We are having website based on big commerce and we can only use react.js to customize checkout page.

We are haivng amazon pay button and like to use `offAmazonPayments.SetOrderReferenceDetails` , here is the link of amazon https://developer.amazon.com/ja/docs/amazon-pay-api/setorderreferencedetails.html

Can we use offAmazonPayments with this package in react.js ?

**Comment by bhushankumarl** [comment]
@hiren-ganatra 
This NodeJs package is aimed to prepare for the only Amazon Marketplace Web Service, not for the Amazon Pay.
