### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by dbuddhadev** [bhushankumarl/amazon-mws#93]
TypeError: __webpack_require__(...).createServer is not a function

./node_modules/amazon-mws/lib/amazon-mws.js/<
C:/Users/dbudd/OneDrive - inc/Development/mws-test/node_modules/amazon-mws/lib/amazon-mws.js:9

   6 | AmazonMws.DEFAULT_RESPONSE_FORMAT = 'JSON';
   7 | AmazonMws.DEFAULT_API_VERSION = null; // Use node's default timeout:
   8 | 
>  9 | AmazonMws.DEFAULT_TIMEOUT = require('http').createServer().timeout;
  10 | AmazonMws.PACKAGE_VERSION = require('../package.json').version;
  11 | AmazonMws.USER_AGENT = {
  12 |   bindings_version: AmazonMws.PACKAGE_VERSION,

**Comment by bhushankumarl** [comment]
@dbuddhadev 
We are not facing the same error on any Node version.
Can you add sample code and more details about specific NodeJs version?
