### ISSUE TITLE
ListInventorySupply not working?

### ISSUE THREAD

**Issue by robot110011** [bhushankumarl/amazon-mws#97]
Tried to use `amazonMWS.fulfillmentInventory.search` but returned nothing. Using scratchpad ListInventorySupply I can get all the info I need, so I think something is wrong in the code.

Response:

`MarketplaceId: 'ATVPDKIKX0DER',
  InventorySupplyList: {},
  ResponseMetadata: { RequestId: '5cd42d84-2c52-4f02-95db-3b077390900c' },
  Headers:
   { 'x-mws-quota-max': 'unknown',
     'x-mws-quota-remaining': 'unknown',
     'x-mws-quota-resetson': 'unknown',
     'x-mws-timestamp': '2019-07-25T15:55:39.330Z',
     'content-type': 'text/xml',
     'content-charset': 'utf-8',
     'content-length': '371',
     'content-md5': 'unknown',
     date: 'Thu, 25 Jul 2019 15:55:39 GMT' },
  StatusCode: 200 }`

**Comment by smdufb** [comment]
Works fine for me.

Did you set `SellerSkus` or `QueryStartDateTime`?

This API only queries your FBA supply. So you will get an empty response when you don't have any (or if it hasn't changed since `QueryStartDateTime`).

**Comment by robot110011** [comment]
Thanks,

It's actually huge recommended from the community to use moment because Date() in node it's just too overcomplicated.

Thanks for taking the time to reply the issue!
